"""
Physical data for the Alpha Centauri star system.

Mass values are in kilograms.
Radius values are in metres.
Average distance values are in metres.
Average velocity values are in metres per second.

Distances and velocities are simplified circular-orbit approximations.
"""

# Shared constants
ASTRONOMICAL_UNIT = 149_597_870_700
SOLAR_MASS = 1.9885e30
SOLAR_RADIUS = 696_340_000
EARTH_MASS = 5.97237e24
EARTH_RADIUS = 6_371_000

# Alpha Centauri A
ALPHA_CENTAURI_A = "Alpha Centauri A"
ALPHA_CENTAURI_A_MASS = 1.1 * SOLAR_MASS
ALPHA_CENTAURI_A_RADIUS = 1.2234 * SOLAR_RADIUS
ALPHA_CENTAURI_A_AVERAGE_DISTANCE = 10.55 * ASTRONOMICAL_UNIT
ALPHA_CENTAURI_A_AVERAGE_VELOCITY = 3_900

# Alpha Centauri B
ALPHA_CENTAURI_B = "Alpha Centauri B"
ALPHA_CENTAURI_B_MASS = 0.9 * SOLAR_MASS
ALPHA_CENTAURI_B_RADIUS = 0.8632 * SOLAR_RADIUS
ALPHA_CENTAURI_B_AVERAGE_DISTANCE = 12.75 * ASTRONOMICAL_UNIT
ALPHA_CENTAURI_B_AVERAGE_VELOCITY = 4_750

# Proxima Centauri
PROXIMA_CENTAURI = "Proxima Centauri"
PROXIMA_CENTAURI_MASS = 0.1221 * SOLAR_MASS
PROXIMA_CENTAURI_RADIUS = 0.1542 * SOLAR_RADIUS
PROXIMA_CENTAURI_AVERAGE_DISTANCE = 12_950 * ASTRONOMICAL_UNIT
PROXIMA_CENTAURI_AVERAGE_VELOCITY = 680

# Proxima Centauri b
PROXIMA_CENTAURI_B = "Proxima Centauri b"
PROXIMA_CENTAURI_B_MASS = 1.055 * EARTH_MASS
PROXIMA_CENTAURI_B_RADIUS = 1.02 * EARTH_RADIUS
PROXIMA_CENTAURI_B_AVERAGE_DISTANCE = 0.04848 * ASTRONOMICAL_UNIT
PROXIMA_CENTAURI_B_AVERAGE_VELOCITY = 47_100

# Proxima Centauri c
PROXIMA_CENTAURI_C = "Proxima Centauri c"
PROXIMA_CENTAURI_C_MASS = 5.8 * EARTH_MASS
PROXIMA_CENTAURI_C_RADIUS = 2.5 * EARTH_RADIUS
PROXIMA_CENTAURI_C_AVERAGE_DISTANCE = 1.489 * ASTRONOMICAL_UNIT
PROXIMA_CENTAURI_C_AVERAGE_VELOCITY = 8_400

# Proxima Centauri d
PROXIMA_CENTAURI_D = "Proxima Centauri d"
PROXIMA_CENTAURI_D_MASS = 0.26 * EARTH_MASS
PROXIMA_CENTAURI_D_RADIUS = 0.8 * EARTH_RADIUS
PROXIMA_CENTAURI_D_AVERAGE_DISTANCE = 0.02885 * ASTRONOMICAL_UNIT
PROXIMA_CENTAURI_D_AVERAGE_VELOCITY = 61_300
