"""
Shared constants for the astronomical simulator.
"""

# Physics constants
GRAVITATIONAL_CONSTANT = 6.67430e-11  # m^3 kg^-1 s^-2

# Distance constants
ASTRONOMICAL_UNIT = 149_597_870_700  # metres

# Time constants
SECONDS_IN_DAY = 86_400
EPOCH_START = "2026-Jan-01 00:00"
EPOCH_STOP = "2026-Jan-02 00:00"

# Visual scaling
DISTANCE_SCALE = 50 / ASTRONOMICAL_UNIT
RADIUS_SCALE = DISTANCE_SCALE

ARTISTIC_RADIUS_SCALE = 1000 / ASTRONOMICAL_UNIT
ARTISTIC_MOON_DISTANCE_SCALE = 500 / ASTRONOMICAL_UNIT

# Trail markers
TRAIL_GAP_POINTS = 1
TRAIL_POINTS_PER_SIMULATED_DAY = 5

MIN_DYNAMIC_TRAIL_MARKER_COUNT = 30
MAX_DYNAMIC_TRAIL_MARKER_COUNT = 600
TRAIL_ORBIT_FRACTION = 0.25

STAR_TRAIL_MARKER_RADIUS = 0.1
PLANET_TRAIL_MARKER_RADIUS = 0.1
MOON_TRAIL_MARKER_RADIUS = 0.05

MIN_TRAIL_MARKER_RADIUS_SCALE = 0.25
MAX_TRAIL_MARKER_RADIUS_SCALE = 5.0
DEFAULT_TRAIL_MARKER_RADIUS_SCALE = 1.0
TRAIL_MARKER_RADIUS_SCALE_STEP = 0.25

# Simulation settings
RENDER_RATE = 60

MIN_DAYS_PER_SECOND = 1
MAX_DAYS_PER_SECOND = 60
DEFAULT_DAYS_PER_SECOND = 30
