"""
Shared constants for the astronomical simulator.
"""

# Physics constants
GRAVITATIONAL_CONSTANT = 6.67430e-11  # m^3 kg^-1 s^-2

# Distance constants
ASTRONOMICAL_UNIT = 149_597_870_700  # metres

# Time constants
SECONDS_IN_DAY = 86_400

# Visual scaling
DISTANCE_SCALE = 50 / ASTRONOMICAL_UNIT

REALISTIC_MOON_DISTANCE_SCALE = DISTANCE_SCALE
ARTISTIC_MOON_DISTANCE_SCALE = 500 / ASTRONOMICAL_UNIT

REALISTIC_RADIUS_SCALE = DISTANCE_SCALE
ARTISTIC_RADIUS_SCALE = 1000 / ASTRONOMICAL_UNIT

# STAR_RADIUS_SCALE = 300 / ASTRONOMICAL_UNIT
# PLANET_RADIUS_SCALE = 300 / ASTRONOMICAL_UNIT
# MOON_RADIUS_SCALE = 300 / ASTRONOMICAL_UNIT

STAR_RADIUS_SCALE = ARTISTIC_RADIUS_SCALE
PLANET_RADIUS_SCALE = ARTISTIC_RADIUS_SCALE
MOON_RADIUS_SCALE = ARTISTIC_RADIUS_SCALE

MIN_PLANET_RADIUS_SCALE = 0.5
MIN_MOON_RADIUS_SCALE = 0.1

STAR_TRAIL_MAX_LENGTH = 2000
PLANET_TRAIL_MAX_LENGTH = 1200
MOON_TRAIL_MAX_LENGTH = 1200

STAR_TRAIL_MAX_WIDTH = 0.1
PLANET_TRAIL_MAX_WIDTH = 0.1
MOON_TRAIL_MAX_WIDTH = 0.05

# Simulation settings
RENDER_RATE = 60

MIN_DAYS_PER_SECOND = 1
MAX_DAYS_PER_SECOND = 60
DEFAULT_DAYS_PER_SECOND = 30
